# Deployment | CPU-bound | 500m CPU | 256Mi memory
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bench-cpu-500m
  namespace: energetiscope-bench
  labels:
    app: energetiscope-bench
    bench-profile: cpu
    bench-cpu: "500m"
    bench-mem: "256Mi"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: energetiscope-bench
      bench-workload: bench-cpu-500m
  template:
    metadata:
      labels:
        app: energetiscope-bench
        bench-workload: bench-cpu-500m
    spec:
      containers:
        - name: stressor
          image: alexeiled/stress-ng:latest
          command: ["stress-ng", "--cpu", "1", "--cpu-load", "50", "--timeout", "600s", "--metrics-brief"]
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
      terminationGracePeriodSeconds: 5
